language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yyfmichaelyan/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true yyfmichaelyan/react-test npm test

after_success:
  - docker build -t yyfmichaelyan/multi-client ./client
  - docker build -t yyfmichaelyan/multi-nginx ./nginx
  - docker build -t yyfmichaelyan/multi-server ./server
  - docker build -t yyfmichaelyan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push yyfmichaelyan/multi-client
  - docker push yyfmichaelyan/multi-nginx
  - docker push yyfmichaelyan/multi-server
  - docker push yyfmichaelyan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-694522955719
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
