language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yyfmichaelyan/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true yyfmichaelyan/react-test npm test

after_success:
  - docker build -t yyfmichaelyan/multi-client ./client
  - docker build -t yyfmichaelyan/multi-nginx ./nginx
  - docker build -t yyfmichaelyan/multi-server ./server
  - docker build -t yyfmichaelyan/multi-worker ./worker
